# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_facebookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookid',
            name='pi_id',
            field=models.IntegerField(unique=True),
        ),
    ]
