# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_pi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=200, unique=True)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
    ]
